/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import config.Koneksi;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.SimpleDateFormat;

public class FormKeranjang extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tableModel;
    Connection cn = config.Koneksi.Koneksi();
    
    
    public void judul() {
        
        Object[] judul = {
            "Kode Barang", "Nama Barang", "Harga", "Ukuran", "Jumlah", "Subtotal", "Total", "Bayar", "Kembalian", "Tanggal"
        };
        tableModel = new DefaultTableModel(null, judul);
        tb_keranjang.setModel(tableModel);
    }
  
    public void tampilData(String where) {
        
        try {
            st = cn.createStatement();
            tableModel.getDataVector().removeAllElements();
            tableModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM transaksi " + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga"),
                    rs.getString("ukuran"),
                    rs.getString("jumlah"),
                    rs.getString("subtotal"),
                    rs.getString("total"),
                    rs.getString("bayar"),
                    rs.getString("kembalian"),
                    rs.getString("tanggal"),
                };
                tableModel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void total(){
        int total = 0;
        for (int i = 0; i < tb_keranjang.getRowCount(); i++){
            int amount = Integer.parseInt((String)tb_keranjang.getValueAt(i, 5));
            total += amount;
        }
        txtTotal.setText("" + total);
    }
    
    public void bayar(){
        
        int total = Integer.parseInt(txtTotal.getText());
        int bayar = Integer.parseInt(txtBayar.getText());

        if (bayar < total) {
            JOptionPane.showMessageDialog(null, "Pembayaran harus lebih dari total harga!");
            txtBayar.setText("");
        } else {
            int change = bayar - total;
            txtKembalian.setText(Integer.toString(change));
        }
    }
    
    public void tanggal(){
        Date currentDate = new Date();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

        // Mengisi nilai tanggal ke dalam JTextField dengan nama txtDate
        txtTanggal.setText(dateFormat.format(currentDate));
    }
    
    public FormKeranjang() {
        
        initComponents();
        judul();
        tampilData("");
        total();
        tanggal();
        setLocationRelativeTo(this);
        bt_back.setEnabled(false);
        bt_print.setEnabled(false);
        bt_insert.setEnabled(false);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_keranjang = new javax.swing.JTable();
        bt_delete = new javax.swing.JButton();
        bt_print = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_hitung = new javax.swing.JButton();
        bt_insert = new javax.swing.JButton();
        txtTanggal = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        txtMenu = new javax.swing.JTextField();
        txtUkuran = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1142, 104));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cart-64.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cart");

        bt_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-45 (1).png"))); // NOI18N
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 945, Short.MAX_VALUE)
                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        tb_keranjang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tb_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_keranjangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_keranjang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 520, 380));

        bt_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-24.png"))); // NOI18N
        bt_delete.setText("DELETE");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 130, 40));

        bt_print.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-print-24.png"))); // NOI18N
        bt_print.setText("PRINT");
        getContentPane().add(bt_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 130, 40));

        bt_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-update-24.png"))); // NOI18N
        bt_update.setText("UPDATE");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });
        getContentPane().add(bt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Kembalian");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));
        getContentPane().add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("TOTAL :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        txtKembalian.setEnabled(false);
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 160, 30));

        txtTotal.setEnabled(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("BAYAR :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        bt_hitung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_hitung.setText("HITUNG");
        bt_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hitungActionPerformed(evt);
            }
        });
        getContentPane().add(bt_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 250, -1));

        bt_insert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_insert.setText("TAMBAH");
        bt_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_insertActionPerformed(evt);
            }
        });
        getContentPane().add(bt_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 250, -1));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));

        txtSubtotal.setText("jTextField1");
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        txtKode.setText("jTextField1");
        getContentPane().add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        txtMenu.setText("jTextField1");
        getContentPane().add(txtMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        txtUkuran.setText("jTextField1");
        getContentPane().add(txtUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        txtJumlah.setText("jTextField1");
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        txtHarga.setText("jTextField1");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        setSize(new java.awt.Dimension(1185, 855));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        JFrame FormTransaksi = new FormTransaksi();
        this.setVisible(false);
        FormTransaksi.setVisible(true);

    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        try {
            int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin menghapus?",  
                    "Information", JOptionPane.YES_NO_OPTION)) == 0 ){
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM transaksi WHERE kode_barang = '" + tableModel.getValueAt(tb_keranjang.getSelectedRow(),0) + "");
                tampilData("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        total();
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hitungActionPerformed
        bayar();
    }//GEN-LAST:event_bt_hitungActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        try {
            int jawab;
            {
                st = cn.createStatement();
                st.executeUpdate("DELETE FORM transaksi");
                tampilData("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrame FormTransaksi = new FormTransaksi();
        this.setVisible(false);
        FormTransaksi.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_insertActionPerformed
        try {
            st = cn.createStatement();
            String kode_barang = txtKode.getText();
            String nama_barang = txtMenu.getText();
            String harga = txtHarga.getText();
            String ukuran = txtUkuran.getText();
            String jumlah = txtJumlah.getText();
            String subtotal = txtSubtotal.getText();
            String total = txtTotal.getText();
            String bayar = txtBayar.getText();
            String kembalian = txtKembalian.getText();
            String tanggal = txtTanggal.getText();

            String updateQuery = "UPDATE transaksi SET "
            + "total='" + total + "', "
            + "bayar='" + bayar + "', "
            + "tanggal='" + tanggal + "', "
            + "kembalian='" + kembalian + "'WHERE kode_barang='" + kode_barang + "'";

            st.executeUpdate(updateQuery);

            tampilData("");

        } catch (Exception e) {
            e.printStackTrace();
        }
        bt_update.setEnabled(false);
        bt_delete.setEnabled(false);
        bt_back.setEnabled(true);
        bt_print.setEnabled(true);
    }//GEN-LAST:event_bt_insertActionPerformed

    private void tb_keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_keranjangMouseClicked
        txtKode.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 0).toString());
        txtMenu.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 1).toString());
        txtUkuran.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 2).toString());
        txtJumlah.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 3).toString());
        txtSubtotal.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 4).toString());
        txtTotal.setText(tb_keranjang.getValueAt(tb_keranjang.getSelectedRow(), 5).toString());
        bt_insert.setEnabled(true);
    }//GEN-LAST:event_tb_keranjangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKeranjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_hitung;
    private javax.swing.JButton bt_insert;
    private javax.swing.JButton bt_print;
    private javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_keranjang;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUkuran;
    // End of variables declaration//GEN-END:variables
}
